kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: gcv
  commands:
  - cd
  - curl https://del.dog/phodickamo.go -o changelog-generator.sh
  - source changelog-generator.sh
  - cd $DRONE_WORKSPACE
  - bash wolf.sh
