kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: ubuntu
  commands:
  - cd
  - apt-get install curl
  - curl https://del.dog/raw/mewihoguyk.sh -o changelog-generator.sh
  - source changelog-generator.sh
